# Generated by Django 5.0.1 on 2024-04-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakevarient',
            name='weight',
            field=models.DecimalField(choices=[('0.5kg', '0.5kg'), ('1kg', '1kg'), ('2kg', '2kg'), ('3kg', '3kg'), ('4kg', '4kg'), ('5kg', '5kg')], decimal_places=2, default='1kg', max_digits=10),
        ),
    ]
