# Generated by Django 5.0.1 on 2024-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cakevarient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakevarient',
            name='weight',
            field=models.DecimalField(choices=[('0.5', '0.5kg'), ('1', '1kg'), ('2', '2kg'), ('3', '3kg'), ('4', '4kg'), ('5', '5kg')], decimal_places=2, default=1, max_digits=10),
        ),
    ]
