# Generated by Django 5.0.1 on 2024-04-15 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cakevarient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='flavour_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.flavour'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='occasion_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.occasion'),
        ),
    ]
