# Generated by Django 5.0.1 on 2024-04-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_basketitem_flavour_object_basketitem_is_order_placed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='flavour_object',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='occasion_object',
        ),
        migrations.AlterField(
            model_name='cakevarient',
            name='shape',
            field=models.CharField(choices=[('round', 'round'), ('square', 'square'), ('rectangle', 'rectangle'), ('heart', 'heart'), ('custom', 'custom')], default='round', max_length=200),
        ),
    ]
