# Generated by Django 5.0.1 on 2024-05-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_shape_remove_cakevarient_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='shape_object',
            field=models.ManyToManyField(to='store.shape'),
        ),
    ]
