# Generated by Django 5.0.1 on 2024-05-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cake_shape_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='shape_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shape'),
        ),
    ]
