# Generated by Django 5.0.1 on 2024-05-20 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_orderitems_status_order_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='flavour_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.flavour'),
        ),
    ]
